/**
 * Enterprise permission matrix (Phase 1).
 * Routes may still reference legacy names; use hasPermission() for checks.
 */

const PERMISSIONS = Object.freeze({
  DASHBOARD_VIEW: 'dashboard:view',
  ENDPOINT_VIEW: 'endpoint:view',
  ENDPOINT_MANAGE: 'endpoint:manage',
  ENDPOINT_SOFTWARE_VIEW: 'endpoint:software:view',
  ENDPOINT_SOFTWARE_MANAGE: 'endpoint:software:manage',
  ALERT_VIEW: 'alert:view',
  ALERT_TRIAGE: 'alert:triage',
  ALERT_MANAGE: 'alert:manage',
  INCIDENT_VIEW: 'incident:view',
  INCIDENT_MANAGE: 'incident:manage',
  DETECTION_VIEW: 'detection:view',
  DETECTION_MANAGE: 'detection:manage',
  DETECTION_AUTHOR: 'detection:author',
  DETECTION_TEST: 'detection:test',
  DETECTION_REVIEW: 'detection:review',
  DETECTION_APPROVE: 'detection:approve',
  DETECTION_PUBLISH: 'detection:publish',
  DETECTION_ROLLBACK: 'detection:rollback',
  DETECTION_REPLAY: 'detection:replay',
  DETECTION_SUPPRESS: 'detection:suppress',
  DETECTION_QUALITY_VIEW: 'detection:quality:view',
  DETECTION_COVERAGE_VIEW: 'detection:coverage:view',
  RESPONSE_VIEW: 'response:view',
  RESPONSE_REQUEST: 'response:request',
  RESPONSE_APPROVE: 'response:approve',
  RESPONSE_EXECUTE: 'response:execute',
  RESPONSE_RTR: 'response:rtr',
  HUNTING_VIEW: 'hunting:view',
  HUNTING_RUN: 'hunting:run',
  IOC_VIEW: 'ioc:view',
  IOC_MANAGE: 'ioc:manage',
  TENANT_VIEW: 'tenant:view',
  TENANT_MANAGE: 'tenant:manage',
  USER_VIEW: 'user:view',
  USER_MANAGE: 'user:manage',
  AUDIT_VIEW: 'audit:view',
  AUDIT_EXPORT: 'audit:export',
  INTEGRATION_VIEW: 'integration:view',
  INTEGRATION_MANAGE: 'integration:manage',
  SYSTEM_HEALTH_VIEW: 'system:health:view',
  SYSTEM_SETTINGS_MANAGE: 'system:settings:manage',
  REPORT_VIEW: 'report:view',
  REPORT_CREATE: 'report:create',
  REPORT_EXPORT: 'report:export',
  REPORT_DELETE: 'report:delete',
  SYSTEM_ADMIN: 'system:admin',
  SOFTWARE_VIEW: 'software:view',
  SOFTWARE_MANAGE: 'software:manage',
  SOFTWARE_VULN_MANAGE: 'software:vulnerability:manage',
  SOFTWARE_NOTIFY: 'software:notify',
  SOFTWARE_BLOCK: 'software:block',
  SOFTWARE_UNBLOCK: 'software:unblock',
  SOFTWARE_ACCEPT_RISK: 'software:accept_risk',
  SOFTWARE_EXPORT: 'software:export',
  SOFTWARE_POLICY_MANAGE: 'software:policy:manage',
});

const ROLES = Object.freeze({
  SUPER_ADMIN: 'super_admin',
  TENANT_ADMIN: 'tenant_admin',
  SOC_MANAGER: 'soc_manager',
  SENIOR_ANALYST: 'senior_analyst',
  ANALYST: 'analyst',
  DETECTION_ENGINEER: 'detection_engineer',
  DETECTION_REVIEWER: 'detection_reviewer',
  READ_ONLY: 'read_only',
  VIEWER: 'viewer',
  AUDITOR: 'auditor',
});

/** Default enterprise role → permissions (DB may override via role_permissions). */
const ROLE_PERMISSION_DEFAULTS = Object.freeze({
  [ROLES.SUPER_ADMIN]: ['*'],
  [ROLES.TENANT_ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ENDPOINT_VIEW,
    PERMISSIONS.ENDPOINT_MANAGE,
    PERMISSIONS.ALERT_VIEW,
    PERMISSIONS.ALERT_TRIAGE,
    PERMISSIONS.INCIDENT_VIEW,
    PERMISSIONS.INCIDENT_MANAGE,
    PERMISSIONS.DETECTION_VIEW,
    PERMISSIONS.DETECTION_MANAGE,
    PERMISSIONS.RESPONSE_VIEW,
    PERMISSIONS.RESPONSE_REQUEST,
    PERMISSIONS.RESPONSE_APPROVE,
    PERMISSIONS.RESPONSE_EXECUTE,
    PERMISSIONS.HUNTING_VIEW,
    PERMISSIONS.HUNTING_RUN,
    PERMISSIONS.IOC_VIEW,
    PERMISSIONS.IOC_MANAGE,
    PERMISSIONS.TENANT_VIEW,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_CREATE,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.SOFTWARE_VIEW,
    PERMISSIONS.SOFTWARE_MANAGE,
    PERMISSIONS.SOFTWARE_VULN_MANAGE,
    PERMISSIONS.SOFTWARE_NOTIFY,
    PERMISSIONS.SOFTWARE_BLOCK,
    PERMISSIONS.SOFTWARE_UNBLOCK,
    PERMISSIONS.SOFTWARE_ACCEPT_RISK,
    PERMISSIONS.SOFTWARE_EXPORT,
    PERMISSIONS.SOFTWARE_POLICY_MANAGE,
  ],
  [ROLES.SOC_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ENDPOINT_VIEW,
    PERMISSIONS.ENDPOINT_MANAGE,
    PERMISSIONS.ALERT_VIEW,
    PERMISSIONS.ALERT_TRIAGE,
    PERMISSIONS.INCIDENT_VIEW,
    PERMISSIONS.INCIDENT_MANAGE,
    PERMISSIONS.DETECTION_VIEW,
    PERMISSIONS.DETECTION_MANAGE,
    PERMISSIONS.RESPONSE_VIEW,
    PERMISSIONS.RESPONSE_REQUEST,
    PERMISSIONS.RESPONSE_APPROVE,
    PERMISSIONS.RESPONSE_EXECUTE,
    PERMISSIONS.HUNTING_VIEW,
    PERMISSIONS.HUNTING_RUN,
    PERMISSIONS.IOC_VIEW,
    PERMISSIONS.IOC_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_CREATE,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.SOFTWARE_VIEW,
    PERMISSIONS.SOFTWARE_NOTIFY,
    PERMISSIONS.SOFTWARE_BLOCK,
    PERMISSIONS.SOFTWARE_UNBLOCK,
    PERMISSIONS.SOFTWARE_ACCEPT_RISK,
    PERMISSIONS.SOFTWARE_EXPORT,
  ],
  [ROLES.SENIOR_ANALYST]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ENDPOINT_VIEW,
    PERMISSIONS.ALERT_VIEW,
    PERMISSIONS.ALERT_TRIAGE,
    PERMISSIONS.INCIDENT_VIEW,
    PERMISSIONS.INCIDENT_MANAGE,
    PERMISSIONS.DETECTION_VIEW,
    PERMISSIONS.RESPONSE_VIEW,
    PERMISSIONS.RESPONSE_REQUEST,
    PERMISSIONS.RESPONSE_EXECUTE,
    PERMISSIONS.HUNTING_VIEW,
    PERMISSIONS.HUNTING_RUN,
    PERMISSIONS.IOC_VIEW,
    PERMISSIONS.SOFTWARE_VIEW,
    PERMISSIONS.SOFTWARE_NOTIFY,
    PERMISSIONS.SOFTWARE_BLOCK,
  ],
  [ROLES.ANALYST]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ENDPOINT_VIEW,
    PERMISSIONS.ALERT_VIEW,
    PERMISSIONS.ALERT_TRIAGE,
    PERMISSIONS.INCIDENT_VIEW,
    PERMISSIONS.DETECTION_VIEW,
    PERMISSIONS.RESPONSE_VIEW,
    PERMISSIONS.RESPONSE_REQUEST,
    PERMISSIONS.HUNTING_VIEW,
    PERMISSIONS.IOC_VIEW,
    PERMISSIONS.SOFTWARE_VIEW,
    PERMISSIONS.SOFTWARE_NOTIFY,
  ],
  [ROLES.READ_ONLY]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ENDPOINT_VIEW,
    PERMISSIONS.ALERT_VIEW,
    PERMISSIONS.INCIDENT_VIEW,
    PERMISSIONS.DETECTION_VIEW,
    PERMISSIONS.HUNTING_VIEW,
    PERMISSIONS.IOC_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.SOFTWARE_VIEW,
  ],
  [ROLES.AUDITOR]: [
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.ALERT_VIEW,
    PERMISSIONS.INCIDENT_VIEW,
    PERMISSIONS.ENDPOINT_VIEW,
    PERMISSIONS.SOFTWARE_VIEW,
    PERMISSIONS.SOFTWARE_EXPORT,
  ],
  [ROLES.DETECTION_ENGINEER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DETECTION_VIEW,
    PERMISSIONS.DETECTION_AUTHOR,
    PERMISSIONS.DETECTION_TEST,
    PERMISSIONS.DETECTION_REPLAY,
    PERMISSIONS.DETECTION_SUPPRESS,
    PERMISSIONS.DETECTION_QUALITY_VIEW,
    PERMISSIONS.DETECTION_COVERAGE_VIEW,
    PERMISSIONS.ALERT_VIEW,
  ],
  [ROLES.DETECTION_REVIEWER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DETECTION_VIEW,
    PERMISSIONS.DETECTION_REVIEW,
    PERMISSIONS.DETECTION_APPROVE,
    PERMISSIONS.DETECTION_PUBLISH,
    PERMISSIONS.DETECTION_ROLLBACK,
    PERMISSIONS.DETECTION_QUALITY_VIEW,
    PERMISSIONS.DETECTION_COVERAGE_VIEW,
    PERMISSIONS.ALERT_VIEW,
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ENDPOINT_VIEW,
    PERMISSIONS.ALERT_VIEW,
    PERMISSIONS.INCIDENT_VIEW,
    PERMISSIONS.DETECTION_VIEW,
    PERMISSIONS.HUNTING_VIEW,
    PERMISSIONS.IOC_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.SOFTWARE_VIEW,
  ],
});

/**
 * Legacy route middleware names → enterprise permissions that satisfy the check.
 */
const LEGACY_ROUTE_PERMISSION_EXPANSION = Object.freeze({
  'actions:write': [
    PERMISSIONS.RESPONSE_REQUEST,
    PERMISSIONS.RESPONSE_EXECUTE,
    PERMISSIONS.ENDPOINT_MANAGE,
  ],
  'alerts:write': [PERMISSIONS.ALERT_TRIAGE],
  'rules:write': [
    PERMISSIONS.DETECTION_MANAGE,
    PERMISSIONS.DETECTION_AUTHOR,
    PERMISSIONS.DETECTION_TEST,
    PERMISSIONS.DETECTION_REPLAY,
    PERMISSIONS.DETECTION_SUPPRESS,
  ],
  'detection:test': [PERMISSIONS.DETECTION_TEST, PERMISSIONS.DETECTION_MANAGE],
  'detection:replay': [PERMISSIONS.DETECTION_REPLAY, PERMISSIONS.DETECTION_MANAGE],
  'detection:review': [PERMISSIONS.DETECTION_REVIEW, PERMISSIONS.DETECTION_APPROVE],
  'detection:approve': [PERMISSIONS.DETECTION_APPROVE, PERMISSIONS.DETECTION_PUBLISH],
  'detection:suppress': [PERMISSIONS.DETECTION_SUPPRESS, PERMISSIONS.DETECTION_MANAGE],
  'audit:read': [PERMISSIONS.AUDIT_VIEW],
  'report:view': [PERMISSIONS.REPORT_VIEW],
  'report:create': [PERMISSIONS.REPORT_CREATE],
  'report:export': [PERMISSIONS.REPORT_EXPORT],
  'report:delete': [PERMISSIONS.REPORT_DELETE],
  'xdr:read': [PERMISSIONS.HUNTING_VIEW],
  'xdr:write': [PERMISSIONS.HUNTING_RUN, PERMISSIONS.IOC_MANAGE],
  manage_integrations: [PERMISSIONS.TENANT_MANAGE, PERMISSIONS.SYSTEM_ADMIN],
  manage_tenants: [PERMISSIONS.TENANT_MANAGE],
  manage_users: [PERMISSIONS.USER_MANAGE],
  'tenants:read': [PERMISSIONS.TENANT_VIEW, PERMISSIONS.TENANT_MANAGE],
  'tenants:write': [PERMISSIONS.TENANT_MANAGE],
});

/** DB seed names (schema-phase5) → enterprise permissions. */
const DB_PERMISSION_EXPANSION = Object.freeze({
  view_endpoints: [PERMISSIONS.ENDPOINT_VIEW],
  view_alerts: [PERMISSIONS.ALERT_VIEW],
  manage_alerts: [PERMISSIONS.ALERT_TRIAGE],
  manage_incidents: [PERMISSIONS.INCIDENT_MANAGE],
  execute_response: [PERMISSIONS.RESPONSE_EXECUTE, PERMISSIONS.RESPONSE_REQUEST],
  manage_policies: [PERMISSIONS.ENDPOINT_MANAGE],
  manage_users: [PERMISSIONS.USER_MANAGE],
  export_data: [PERMISSIONS.AUDIT_VIEW],
  manage_iocs: [PERMISSIONS.IOC_MANAGE],
  manage_integrations: [PERMISSIONS.TENANT_MANAGE],
  view_audit: [PERMISSIONS.AUDIT_VIEW],
  manage_tenants: [PERMISSIONS.TENANT_MANAGE],
});

function expandPermissionAliases(permission) {
  const out = new Set([permission]);
  const legacy = LEGACY_ROUTE_PERMISSION_EXPANSION[permission];
  if (legacy) legacy.forEach((p) => out.add(p));
  const db = DB_PERMISSION_EXPANSION[permission];
  if (db) db.forEach((p) => out.add(p));
  return out;
}

/**
 * True if userPerms grants `required` (supports *, legacy, and DB permission names).
 */
function hasPermission(userPerms, required) {
  if (!Array.isArray(userPerms) || !required) return false;
  if (userPerms.includes('*')) return true;

  const userExpanded = new Set();
  for (const p of userPerms) {
    expandPermissionAliases(p).forEach((x) => userExpanded.add(x));
    userExpanded.add(p);
  }

  const requiredExpanded = expandPermissionAliases(required);
  if (userExpanded.has(required)) return true;
  for (const r of requiredExpanded) {
    if (userExpanded.has(r)) return true;
  }

  for (const [legacyKey, modernList] of Object.entries(LEGACY_ROUTE_PERMISSION_EXPANSION)) {
    if (legacyKey === required || modernList.includes(required)) {
      if (userPerms.includes(legacyKey)) return true;
      if (modernList.some((m) => userExpanded.has(m))) return true;
    }
  }

  return false;
}

function hasAnyPermission(userPerms, requiredList) {
  return requiredList.some((r) => hasPermission(userPerms, r));
}

module.exports = {
  PERMISSIONS,
  ROLES,
  ROLE_PERMISSION_DEFAULTS,
  LEGACY_ROUTE_PERMISSION_EXPANSION,
  DB_PERMISSION_EXPANSION,
  expandPermissionAliases,
  hasPermission,
  hasAnyPermission,
};
