/**
 * Legacy URL → compact console redirects (preserves query string via RedirectPreserve).
 */
export const LEGACY_REDIRECT_ROUTES = [
  { path: 'dashboard', type: 'navigate', to: '/overview' },
  { path: 'alerts', type: 'preserve', to: '/detections', defaultTab: 'alerts' },
  { path: 'alerts/:id', type: 'legacy-alert' },
  { path: 'triage', type: 'preserve', to: '/detections', defaultTab: 'triage' },
  { path: 'soc/triage', type: 'preserve', to: '/detections', defaultTab: 'triage' },
  { path: 'detection-rules', type: 'preserve', to: '/detections', defaultTab: 'rules' },
  { path: 'detection-rules/new', type: 'navigate', to: '/detections/rules/new' },
  { path: 'detection-rules/:id/edit', type: 'legacy-rule-edit' },
  { path: 'detection-rules/:id', type: 'legacy-rule-detail' },
  { path: 'mitre', type: 'preserve', to: '/detections', defaultTab: 'mitre' },
  { path: 'suppressions', type: 'preserve', to: '/detections', defaultTab: 'suppressions' },
  { path: 'events', type: 'preserve', to: '/hunting', defaultTab: 'events' },
  { path: 'raw-events', type: 'preserve', to: '/hunting', defaultTab: 'raw' },
  { path: 'normalized-events', type: 'preserve', to: '/hunting', defaultTab: 'normalized' },
  { path: 'xdr', type: 'preserve', to: '/overview', defaultTab: 'soc' },
  { path: 'xdr/events', type: 'preserve', to: '/hunting', defaultTab: 'xdr-events' },
  { path: 'xdr/detections', type: 'preserve', to: '/detections', defaultTab: 'xdr' },
  { path: 'xdr/realtime', type: 'preserve', to: '/hunting', defaultTab: 'realtime' },
  { path: 'network', type: 'preserve', to: '/hunting', defaultTab: 'network' },
  { path: 'iocs', type: 'preserve', to: '/hunting', defaultTab: 'iocs' },
  { path: 'process-monitor', type: 'preserve', to: '/endpoints', defaultView: 'processes' },
  { path: 'endpoints/:endpointId/process-tree', type: 'preserve', to: '/endpoints', defaultView: 'process-tree' },
  { path: 'host-timeline', type: 'preserve', to: '/endpoints', defaultView: 'timeline' },
  { path: 'hosts/:endpointId/timeline', type: 'preserve', to: '/endpoints', defaultView: 'timeline' },
  { path: 'host-groups', type: 'preserve', to: '/endpoints', defaultTab: 'groups' },
  { path: 'sensor-health', type: 'preserve', to: '/overview', defaultTab: 'agent-health' },
  { path: 'av', type: 'navigate', to: '/protection' },
  { path: 'av/detections', type: 'preserve', to: '/protection', defaultTab: 'detections' },
  { path: 'av/quarantine', type: 'preserve', to: '/protection', defaultTab: 'quarantine' },
  { path: 'av/scan-tasks', type: 'preserve', to: '/protection', defaultTab: 'scans' },
  { path: 'av/policies', type: 'preserve', to: '/protection', defaultTab: 'policies' },
  { path: 'av/signatures', type: 'preserve', to: '/protection', defaultTab: 'signatures' },
  { path: 'av/reputation', type: 'preserve', to: '/protection', defaultTab: 'reputation' },
  { path: 'av/malware-alerts', type: 'preserve', to: '/detections', defaultTab: 'alerts' },
  { path: 'av/malware-alerts/:id', type: 'legacy-malware-alert' },
  { path: 'incidents', type: 'preserve', to: '/investigation', defaultTab: 'incidents' },
  { path: 'incidents/:id', type: 'legacy-incident' },
  { path: 'investigations', type: 'preserve', to: '/investigation', defaultTab: 'cases' },
  { path: 'investigations/:id', type: 'legacy-case' },
  { path: 'threat-graph', type: 'preserve', to: '/investigation', defaultTab: 'graph' },
  { path: 'respond/approvals', type: 'preserve', to: '/response', defaultTab: 'approvals' },
  { path: 'rtr', type: 'preserve', to: '/response', defaultTab: 'rtr' },
  { path: 'playbooks', type: 'preserve', to: '/response', defaultTab: 'playbooks' },
  { path: 'enterprise', type: 'preserve', to: '/admin', defaultTab: 'settings' },
  { path: 'tenants', type: 'preserve', to: '/admin', defaultTab: 'tenants' },
  { path: 'mssp', type: 'preserve', to: '/overview', defaultTab: 'tenant' },
  { path: 'rbac', type: 'preserve', to: '/admin', defaultTab: 'rbac' },
  { path: 'audit-logs', type: 'preserve', to: '/admin', defaultTab: 'audit' },
  { path: 'reports', type: 'preserve', to: '/admin', defaultTab: 'reports' },
  { path: 'integrations', type: 'preserve', to: '/admin', defaultTab: 'integrations' },
  { path: 'system/health', type: 'preserve', to: '/admin', defaultTab: 'system-health' },
  { path: 'analytics-detections', type: 'preserve', to: '/detections', defaultTab: 'analytics' },
  { path: 'risk', type: 'preserve', to: '/overview', defaultTab: 'executive' },
  { path: 'web-url-protection', type: 'preserve', to: '/hunting', defaultTab: 'web' },
  { path: 'policies', type: 'preserve', to: '/protection', defaultTab: 'policies' },
  { path: 'agent-network-map', type: 'preserve', to: '/endpoints', defaultTab: 'map' },
];
